export const paths = {
  home: '/',
  features: '/features',
  howItWorks: '/how-it-works',
  pricing: '/pricing',
  faq: '/faq',
  contact: '/contact',
  privacy: '/privacy',
  terms: '/terms',
  cookies: '/cookies',
  about: '/about',

  login: '/login',
  register: '/register',
  forgotPassword: '/forgot-password',
  resetPassword: '/reset-password',
  onboarding: '/onboarding',

  dashboard: '/dashboard',
  learners: '/dashboard/learners',
  newLearner: '/dashboard/learners/new',
  learner: (id) => `/dashboard/learners/${id}`,
  editLearner: (id) => `/dashboard/learners/${id}/edit`,
  slots: '/dashboard/slots',
  slot: (id) => `/dashboard/slots/${id}`,
  monitoring: '/dashboard/monitoring',
  newMonitoring: '/dashboard/monitoring/new',
  notifications: '/dashboard/notifications',
  history: '/dashboard/history',
  profile: '/dashboard/profile',
  settings: '/dashboard/settings',
  help: '/dashboard/help',
};
